version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/myapp
      - ./public:/myapp/public
      - ./tmp:/myapp/tmp
      - ./log:/myapp/log
      - bundle_path:/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - BUNDLE_PATH=/bundle
      - "SELENIUM_DRIVER_URL=http://selenium_chrome:4444/wd/hub"
  selenium_chrome:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none
  nginx:
    build: .
    ports:
      - 80:80
    volumes:
      - ./public:/myapp/public
      - ./tmp:/myapp/tmp
    depends_on:
      - web
volumes:
  bundle_path:
